version: 2
registries:
  npm:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    # this should just be a blank space stored in a secret
    token: ${{secrets.GH_DUMMY}}
    replaces-base: true
updates:
  # node updates
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 12
    open-pull-requests-limit: 4
    ignore:
      - dependency-name: 'wrangler'